server:
  address: localhost
  port: 8081

spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
  # 数据库路径
  data:
    mongodb:
      uri: mongodb://localhost:27017/file-server
  # 文件上传限制大小
  servlet:
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB
